export type Stamp = {
  collectedAt: string;
  runtime?: { commit?: string; startedAt?: string; dirty?: boolean } | null;
};
export type Row = {
  key: string;
  kind: "work" | "execution";
  workKey?: string;
  title: string;
  originalTitle?: string;
  id?: string;
  repo: string;
  revision: number;
  state: string;
  stateLabel: string;
  stored?: string;
  healthKind: string;
  healthLabel: string;
  healthReason: string;
  bucket?: string;
  board?: string;
  owner?: string;
  at?: string;
  reportAt?: string;
  reportLabel?: string;
  signalAt?: string;
  signalLabel?: string;
  purpose?: string;
  summary?: string;
  next?: string;
  scope?: string;
  model?: string;
  modelTitle?: string;
  effort?: string;
  flowLabel?: string;
  flowTitle?: string;
  flowPhase?: string;
  rallyStep?: string;
  turnLabel?: string;
  turnReason?: string;
  parentWorkKey?: string;
  failureReason?: string;
};
export type Field = {
  name: string;
  label: string;
  value: string | number;
  type: "text" | "textarea" | "select" | "radio" | "number" | "hidden";
  options: [string, string][] | null;
  required: boolean;
};
export type FormSpec = {
  action: string;
  title: string;
  fields: Field[];
  disabled?: boolean;
};
export type Mail = {
  mailId?: string;
  digest?: string;
  t: string;
  by: string;
  role: string;
  currentSender?: string;
  currentRecipient?: string;
  preview?: string;
  status: string;
  replyStatus?: string;
  read?: boolean;
  executionKey?: string;
  workKey?: string;
  replyTo?: string;
};
export type Decision = {
  id: string;
  card: string;
  revision: number;
  question: string;
  reason: string;
  reasonHtml?: string;
  recommendation: string;
  requestedBy: string;
  at: string;
  options: string[];
  status: string;
  answer?: { text: string; choice?: string; at: string };
  delivery?: { status: string; role?: string; error?: string };
  cancelReason?: string;
};
export type HistoryEntry = {
  at?: string;
  by?: string;
  kind?: string;
  action?: string;
  note?: string;
  progress?: string;
  nextAction?: string;
  result?: string;
  transition?: string;
  turn?: string;
  status?: string;
};
export type DetailData = Stamp & {
  key: string;
  kind: "work" | "execution";
  revision: number;
  title: string;
  row: Row;
  forms: FormSpec[];
  summaryHtml?: string;
  facts: [string, string | null][];
  history: HistoryEntry[];
  mail: Mail[];
  mailTotal: number;
  instructions?: {
    body: string;
    prefixHtml: string;
    sections: { title: string; label: string; content: string; html: string }[];
  };
  report?: { html: string; state: string; at?: string; by?: string };
  runs?: { role?: string; state?: string; result?: string; at?: string }[];
  related?: {
    key: string;
    title: string;
    rallyRound: string;
    rallyStep: string;
    displayState: string;
  }[];
  executions?: { key: string; phase: string; round: number; row: Row | null }[];
};
export type Paged<T> = Stamp & {
  items: T[];
  total: number;
  page: number;
  pages: number;
  pageSize?: number;
};
export type Summary = Stamp & {
  decisions: number | null;
  waiting: number | null;
  counts: { work: number | null; executions: number; unlinked: number };
  errors: string[];
};
