import {escapeHtml as e} from './card-content.mjs';
import {executionHealth,renderExecutionHealth} from './dashboard-execution.mjs';

const stamp=x=>Number.isFinite(Date.parse(x))?new Date(x).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'모름';
const link=c=>`<a data-card-key="${e(c.key)}" href="?card=${encodeURIComponent(c.key)}#detail">${e(c.title||c.id)}</a>`;
function executionCard(c){
 return `<article class="${c.healthKind==='attention'?'st-attn-card':'st-work'}"><div class="st-attn-head">${renderExecutionHealth(c)}<strong>${link(c)}</strong></div><p>${e(c.healthReason)}</p><p class="st-attn-meta">담당 ${e(c.role||'미배정')} · ${e(c.board||'판 미지정')} · ${e(c.signalLabel)} ${e(c.signalAt?stamp(c.signalAt):'')}</p>${c.nextAction?`<p>다음 행동: ${e(c.nextAction)}</p>`:''}</article>`;
}
function workCard(w){
 return `<article class="st-work"><div class="st-work-top">${renderExecutionHealth(w)}<span class="st-work-board">${e(w.board||w.repo)} · ${e(w.flowLabel)}</span><span class="st-work-prog">${e(w.flowPhase)}</span></div><h3 class="st-work-title">${link(w)}</h3>${w.purpose?`<p class="st-work-purpose">${e(w.purpose)}</p>`:''}<p>${e(w.healthReason)}</p><dl class="st-work-grid"><dt>지금 차례</dt><dd class="st-turn">${e(w.turnLabel)}</dd><dt>다음 행동</dt><dd>${e(w.next)}</dd></dl><div class="st-work-foot"><span>최근 실행 신호 ${e(w.signalLabel||'없음')} ${e(w.signalAt?stamp(w.signalAt):'')}</span><span class="st-when">업무 기록 ${e(w.reportLabel)}</span>${w.summary?`<span class="st-sum">${e(w.summary)}</span>`:''}</div></article>`;
}
export function renderDashboardStatus({center,works,workError=null,decisions=[],decisionError=null,collectedAt=null}){
 const executions=(center?.cards||[]).filter(c=>c.workType!=='coordination').map(c=>({...c,...executionHealth(c)}));
 const byKind=kind=>executions.filter(c=>c.healthKind===kind);
 const attention=byKind('attention'),running=byKind('running'),waiting=byKind('waiting');
 const open=(works||[]).filter(w=>w.state==='running'),held=(works||[]).filter(w=>w.state==='hold'),closed=(works||[]).filter(w=>['done','cancelled'].includes(w.state));
 const chip=(kind,href,num,label)=>`<a class="st-chip st-c-${kind}" href="${href}"><span class="st-num">${num}</span><span class="st-lbl">${label}</span></a>`;
 const list=items=>items.length<=8?items.map(executionCard).join(''):items.slice(0,8).map(executionCard).join('')+`<details class="st-fold"><summary>나머지 ${items.length-8}장</summary>${items.slice(8).map(executionCard).join('')}</details>`;
 const section=(id,title,items,hint)=>`<section id="${id}" class="st-section"><header class="st-sec-head"><h2>${title}</h2><span class="st-cnt${id==='status-attention'?' st-cnt-attn':''}">${center?items.length+'건':'모름'}</span><span class="st-hint">${hint}</span></header>${!center?'<p class="st-error">카드 기록을 읽지 못해 확인 필요 수를 계산하지 않았습니다.</p>':items.length?list(items):'<p class="st-empty">해당 실행이 없습니다.</p>'}</section>`;
 const monitor=center?.monitoring;
 const monitorLabel=!monitor?'감시 정보 미수집':monitor.process?.state==='running'?'감시 프로세스 실행 중':monitor.process?.state==='absent'?'감시 프로세스 없음':'감시 프로세스 확인 필요';
 return `<div data-view="status" class="st-view">
 <header class="st-lead"><h1>지금 작업이 어떻게 진행되고 있나요?</h1><p>발령·진행 보고·결과와 담당 세션을 함께 봅니다. 카드 수정 시각은 실행 신호가 아닙니다.</p><small>수집 ${e(stamp(collectedAt))} · <a href="#boards">${e(monitorLabel)}</a> · 감시 주기 정상 여부는 별도 확인이 필요합니다.</small></header>
 <div class="st-band" role="group" aria-label="지금 상황 요약">${chip('run','#status-executing',center?running.length:'모름','작업 중')}${chip('wait','#status-waiting',center?waiting.length:'모름','결과 대기')}${chip('attn','#status-attention',center?attention.length:'모름','확인 필요')}${chip('decision','#decisions',decisionError?'모름':decisions.filter(d=>d.status==='open').length,'내 결정 대기')}${chip('dim','#status-running',works===null?'모름':open.length,'열린 업무')}${chip('dim','?collection=executions&state=all#dashboard',center?executions.length:'모름','전체 실행 카드')}</div>
 ${section('status-attention','확인 필요',attention,'시작 보고·세션·실패 근거를 확인할 실행입니다. 단순 카드 수정으로 해소되지 않습니다.')}
 ${section('status-executing','작업 중인 실행',running,'현재 담당의 진행 보고와 같은 세션이 확인됩니다. 업무 연결 여부와 관계없이 표시합니다.')}
 ${section('status-waiting','결과를 기다리는 실행',waiting,'담당자가 결과 대기를 보고했습니다. 보고가 오래됐다는 이유만으로 중단으로 보지 않습니다.')}
 <p class="st-hint">${center?`실행 전 ${byKind('planned').length}건 · 보류 ${byKind('hold').length}건`:'실행 전·보류 모름'} · 보고 시각은 실시간 작업 감지가 아닙니다.</p>
 <section id="status-running" class="st-section"><header class="st-sec-head"><h2>열린 업무</h2><span class="st-cnt">${works===null?'모름':open.length+'장'}</span><span class="st-hint">열린 업무도 실행 준비·결과 대기·감독 확인 단계일 수 있습니다.</span></header>${works===null?`<p class="st-error" role="alert">업무 기록을 읽을 수 없습니다${workError?': '+e(workError):'.'}</p>`:open.length?open.map(workCard).join(''):'<p class="st-empty">열린 업무가 없습니다. 위의 실행 목록에서 개별 작업을 확인하세요.</p>'}</section>
 ${held.length?`<section class="st-section"><h2>보류 중인 업무</h2>${held.map(workCard).join('')}</section>`:''}
 ${closed.length?`<details class="st-fold"><summary>끝난 업무 ${closed.length}장</summary>${closed.map(w=>`<p>${link(w)} · ${e(w.stateLabel)}</p>`).join('')}</details>`:''}
 <p class="st-footnote">작업 중·결과 대기·확인 필요 수치는 실행 카드 기준이며 관리·조율 카드는 제외합니다. 제품 완성률이 아닙니다. 상세 비교·정렬은 <a href="?collection=executions#dashboard">작업 표</a>에서 확인하세요.</p></div>`;
}

export const dashboardStatusStyle=[
'.st-view{padding:4px 0 0}.st-band{display:flex;gap:10px;flex-wrap:wrap;margin:8px 0 26px}.st-chip{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid #dfe6e0;border-radius:9px;padding:10px 16px;text-decoration:none;color:#202724;min-width:118px}.st-chip:hover{border-color:#9bb5a6;background:#fbfdfc}.st-chip .st-num{font-size:22px;font-weight:750;line-height:1.1}.st-chip .st-lbl{font-size:12px;color:#536159}.st-chip::before{content:"";width:8px;height:8px;border-radius:50%;background:#cbd2cd;flex-shrink:0}.st-c-attn{background:#fff0d0;border-color:#b68625}.st-c-attn::before{background:#b68625}.st-c-attn .st-num{color:#794e00}.st-c-run::before{background:#e68a27}.st-c-decision::before{background:#158064}',
'.st-section{margin-bottom:28px}.st-sec-head{display:flex;align-items:baseline;gap:12px;margin-bottom:12px;flex-wrap:wrap}.st-sec-head h2{font-size:16px;margin:0;font-weight:750}.st-cnt{font-size:13px;font-weight:700}.st-cnt-attn{color:#794e00}.st-cnt-run{color:#814600}.st-hint{font-size:12px;color:#536159;margin-left:auto}',
'.st-attn-card{background:#fff;border:1px solid #dfe6e0;border-left:4px solid #b68625;border-radius:8px;padding:12px 18px;margin-bottom:10px}.st-attn-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.st-attn-title{font-weight:700;font-size:14px}.st-attn-meta{font-size:12.5px;color:#536159;margin:4px 0 0}',
'.st-work{background:#fff;border:1px solid #dfe6e0;border-radius:10px;padding:18px 22px;margin-bottom:14px}.st-work-top{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:12.5px}.st-work-board{color:#536159}.st-work-prog{margin-left:auto;font-weight:700;font-size:12.5px}.st-work-title{margin:8px 0 2px;font-size:16.5px;font-weight:750;line-height:1.35}.st-work-title a{color:#202724;text-decoration:none}.st-work-title a:hover{text-decoration:underline}.st-work-purpose{font-size:13px;color:#536159;margin:0 0 12px}.st-work-grid{display:grid;grid-template-columns:120px minmax(0,1fr);gap:4px 18px;border-top:1px solid #dfe6e0;padding-top:12px;margin:0}.st-work-grid dt{font-size:11px;font-weight:700;letter-spacing:.04em;color:#536159;padding-top:2px}.st-work-grid dd{font-size:13.5px;margin:0;overflow-wrap:anywhere}.st-work-grid dd.st-turn{font-weight:700}.st-work-foot{margin-top:12px;padding-top:10px;border-top:1px solid #dfe6e0;font-size:12.5px;color:#536159;display:flex;gap:14px;flex-wrap:wrap}.st-work-foot .st-when{font-weight:700;color:#202724;white-space:nowrap}.st-work-foot .st-sum{overflow-wrap:anywhere}',
'.st-fold{border:1px solid #dfe6e0;border-radius:8px;background:#fff;padding:12px 18px;margin-bottom:10px;font-size:13.5px}.st-fold>summary{cursor:pointer;font-weight:600;color:#245c44}.st-hold-row{margin:8px 0;overflow-wrap:anywhere}.st-hold-row small{color:#536159}.st-empty{color:#536159}.st-error{color:#8f251e}.st-footnote{font-size:12px;color:#536159}',
'@media (max-width:800px){.st-band{flex-wrap:nowrap;overflow-x:auto;padding-bottom:6px}.st-chip{flex:0 0 auto}.st-work{padding:14px 16px}.st-work-grid{grid-template-columns:1fr;gap:2px}.st-work-grid dt{margin-top:8px}.st-work-prog{margin-left:0;width:100%}.st-hint{margin-left:0;width:100%}}'
].join('\n')+`.st-lead{margin-bottom:16px}.st-lead h1{font-size:22px}.st-lead p,.st-lead small{font-size:12px;color:#536159}.st-c-wait::before{background:#246a99}.st-c-run::before{background:#22694d}`;
